package Vistas;

import controllers.HospitalRural;
import interfaces.IHospitalRural;
import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Medico;
import models.Sala;

public class AdicionarMedico extends javax.swing.JDialog {

    private ArrayList<String> especialidades = new ArrayList<>();
    private IHospitalRural hospital;
    private ArrayList<String> salas = new ArrayList<>();

//    Declaración de modelos para trabajar con los jTabel
    DefaultTableModel modeloTablaEspecialidades = new DefaultTableModel() {
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };
    DefaultTableModel modeloTablaSalas = new DefaultTableModel() {
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };
    DefaultTableModel modeloTablaSalasTrabaja = new DefaultTableModel() {
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };

    public AdicionarMedico(java.awt.Frame parent, boolean modal, HospitalRural hospital) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setSize(555, 660);
        setLocationRelativeTo(null);
        this.hospital = hospital;

        modeloTablaEspecialidades.addColumn("Especialidades del médico");
        EspcTabla.setModel(modeloTablaEspecialidades);

        modeloTablaSalas.addColumn("Salas");
        jTable_SalasHospital.setModel(modeloTablaSalas);
        for (Sala aux : this.hospital.getSalas()) {
            String[] datos = new String[1];
            datos[0] = aux.getNombre();
            modeloTablaSalas.addRow(datos);
        }

        modeloTablaSalasTrabaja.addColumn("Salas en las que trabaja");
        jTable_SalasTrabaja.setModel(modeloTablaSalasTrabaja);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_SalasHospital = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_SalasTrabaja = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        addEspc = new javax.swing.JButton();
        TextNombre = new javax.swing.JTextField();
        TextNI = new javax.swing.JTextField();
        TextEspc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EspcTabla = new javax.swing.JTable();
        ElimEspc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario para adicionar médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de identidad:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Especialidad:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salas del hospital:");

        jTable_SalasHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_SalasHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_SalasHospitalMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_SalasHospital);

        jTable_SalasTrabaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_SalasTrabaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_SalasTrabajaMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_SalasTrabaja);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sala en la que trabaja:");

        addEspc.setText("adicionar");
        addEspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEspcActionPerformed(evt);
            }
        });

        TextNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNombreKeyTyped(evt);
            }
        });

        TextNI.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNIKeyTyped(evt);
            }
        });

        TextEspc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextEspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEspcActionPerformed(evt);
            }
        });
        TextEspc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextEspcKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del médico:");

        EspcTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(EspcTabla);

        ElimEspc.setText("eliminar");
        ElimEspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimEspcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextEspc)
                            .addComponent(TextNI)
                            .addComponent(TextNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addEspc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ElimEspc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextEspc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEspc)
                    .addComponent(ElimEspc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 510));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceptado.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rechazado.png"))); // NOI18N
        jButton2.setText("cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 270, 70));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 530, 20));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/negro formulario.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String validar = "";
        boolean flap = true;

        if (TextNombre.getText().equals("") || !ValidarCampos.comprobarCamposTexto(TextNombre.getText())) {
            flap = false;
            validar = validar + "\n-Nombre del médico";
        }
        if (!ValidarCampos.comprobarCamposNumericos(TextNI.getText()) || TextNI.getText().length() != 11) {
            flap = false;
            validar = validar + "\n-Número de identidad";
        }

        if (salas.isEmpty()) {
            flap = false;
            validar = validar + "\n-No ha selexionado ninguna Sala";
        }

        for (Medico aux : hospital.getMedicos()) {
            if (TextNI.getText().equals(aux.getCi())) {
                flap = false;
                validar = validar + "\n-Ya existe un médico con el numero de carnet: " + TextNI.getText() + " registrado en el sistema";
            }
        }
        // Si los campos ueron validados correctamente se ingresa al nuevo medico
        if (flap) {
            ArrayList<Sala> salaAux = new ArrayList<>();
            for (Sala aux : hospital.getSalas()) {
                if (salas.contains(aux.getNombre())) {
                    salaAux.add(aux);
                }
            }
            Medico medico = new Medico(TextNombre.getText(), TextNI.getText(), especialidades, salaAux);
            this.hospital.addMedico(medico);
            JOptionPane.showMessageDialog(null, "Se ha añadido correctamente al médico: " + TextNombre.getText());

            // Limpiar campos luego de agregar un paciente al sistema
            ValidarCampos.cleardField(TextEspc);
            ValidarCampos.cleardField(TextNI);
            ValidarCampos.cleardField(TextNombre);
            ValidarCampos.cleardField(modeloTablaEspecialidades);
            ValidarCampos.cleardField(modeloTablaSalasTrabaja);
            ValidarCampos.cleardField(especialidades);
            ValidarCampos.cleardField(salas);
        } else {
            JOptionPane.showMessageDialog(null, "Verifique los siguientes campos que presentan errores:" + validar);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addEspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEspcActionPerformed
        // TODO add your handling code here:
        String[] Espc = new String[1];
        if (!TextEspc.getText().equals("")) {
            if (!especialidades.contains(TextEspc.getText())) {
                this.especialidades.add(TextEspc.getText());
                Espc[0] = TextEspc.getText();
                this.modeloTablaEspecialidades.addRow(Espc);
                TextEspc.setText("");
                TextEspc.setBackground(Color.white);
            } else {
                TextEspc.setText("Especialidad ya existe");
                TextEspc.setBackground(Color.red);
            }
        }
    }//GEN-LAST:event_addEspcActionPerformed

    private void ElimEspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimEspcActionPerformed
        // TODO add your handling code here:
        int fila = EspcTabla.getSelectedRow();
        if (fila >= 0) {
            modeloTablaEspecialidades.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione la especialidad que desea eliminar");
        }
    }//GEN-LAST:event_ElimEspcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Limpiar todos los campos del formulario
        ValidarCampos.cleardField(TextEspc);
        ValidarCampos.cleardField(TextNI);
        ValidarCampos.cleardField(TextNombre);
        ValidarCampos.cleardField(modeloTablaEspecialidades);
        ValidarCampos.cleardField(modeloTablaSalasTrabaja);
        ValidarCampos.cleardField(especialidades);
        ValidarCampos.cleardField(salas);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNIKeyTyped
        char c = evt.getKeyChar();
        if (!ValidarCampos.comprobarCamposNumericos(String.valueOf(c)) || TextNI.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_TextNIKeyTyped

    private void TextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyTyped
        char c = evt.getKeyChar();
        if (!ValidarCampos.comprobarCamposTexto(String.valueOf(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_TextNombreKeyTyped

    private void TextEspcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextEspcKeyTyped
        char c = evt.getKeyChar();
        if (!ValidarCampos.comprobarCamposTexto(String.valueOf(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_TextEspcKeyTyped

    private void TextEspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEspcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEspcActionPerformed

    private void jTable_SalasHospitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SalasHospitalMousePressed
        String[] datos = new String[1];
        datos[0] = String.valueOf(jTable_SalasHospital.getValueAt(jTable_SalasHospital.getSelectedRow(), 0));
        if (!salas.contains(datos[0])) {
            salas.add(datos[0]);
            modeloTablaSalasTrabaja.addRow(datos);
        }
    }//GEN-LAST:event_jTable_SalasHospitalMousePressed

    private void jTable_SalasTrabajaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SalasTrabajaMousePressed
        if (!salas.isEmpty()) {
            salas.remove(String.valueOf(jTable_SalasTrabaja.getValueAt(jTable_SalasTrabaja.getSelectedRow(), 0)));
            modeloTablaSalasTrabaja.removeRow(jTable_SalasTrabaja.getSelectedRow());
        }
    }//GEN-LAST:event_jTable_SalasTrabajaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdicionarMedico dialog = new AdicionarMedico(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ElimEspc;
    private javax.swing.JTable EspcTabla;
    private javax.swing.JTextField TextEspc;
    private javax.swing.JTextField TextNI;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JButton addEspc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_SalasHospital;
    private javax.swing.JTable jTable_SalasTrabaja;
    // End of variables declaration//GEN-END:variables
}
